Update Towny support.
BG-Software-LLC/WildInspect pull request #20
Opened 2022-03-09 17:38 UTC by LlmDl

Towny deprecated getResident(String) in the TownyDataSource a while back and the last release saw the removal of this method.

This PR replaces it with what will be the final method to get a Resident from a player.

This may also be of use:

```
repositories {
    maven {
        name = 'glaremasters repo'
        url = 'https://repo.glaremasters.me/repository/towny/'
    }

dependencies {
    compileOnly 'com.palmergames.bukkit.towny:towny:0.98.0.0'
}
```

2022-03-10 19:32 UTC, OmerBenGera commented
Does this method exist in older versions of Towny as well?

2022-03-10 19:33 UTC, LlmDl commented
The .getUniqueID() might have to be switched over to .getName(), what versions of MC are you supporting currently?

2022-03-10 19:39 UTC, OmerBenGera commented
This patch must work on older versions of Towny from 1.8 up to 1.18.
If it doesn't, then you'll have to support both old and new methods.

2022-03-10 20:29 UTC, LlmDl commented
The legacy versions of Towny that's for 1.8, 1.9, 1.10, 1.11, 1.13 don't have a TownyAPI class, so its already not working on versions that old.

Our legacy 1.12 version does have TownyAPI.getInstance().getResident(player.getName()).

Towny currently supports 1.14 and onwards but in the next release we're switching to MC 1.16 and onwards only.

bStats tells us that everything older than 1.16 is a very, very small percentage of our user-base.

2022-03-10 20:48 UTC, OmerBenGera commented
I see. One thing needs to be done is to update the build.gradle with your repository and I'll merge it :)

2022-03-10 20:49 UTC, LlmDl commented
Cheers, you'll make our mutual users very happy!

2022-03-10 21:09 UTC, OmerBenGera commented
> Cheers, you'll make our mutual users very happy!

Haha :)
Let me know once you made the changes to the build.gradle so I can merge

2022-03-10 21:14 UTC, LlmDl commented
I think that did it, I'm unable to build it to test though.

2022-03-10 21:28 UTC, OmerBenGera requested changes

2022-03-10 21:28 UTC, OmerBenGera commented on build.gradle
> +        maven { url 'https://repo.glaremasters.me/repository/towny/' }
This should go to the build.gradle of Hook_Towny

2022-03-10 21:28 UTC, OmerBenGera commented on build.gradle
> +    compileOnly 'com.palmergames.bukkit.towny:towny:0.98.0.0'
This should go to the build.gradle of Hook_Towny

2022-03-11 06:55 UTC, OmerBenGera approved these changes

2022-03-11 06:56 UTC, merged